### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by luisfcosta2015** [socialsoftware/as-tutor#22]
É importante pensar em aplicar testes. Do lado do servidor o uso é com JUnit ou Spock. Do lado do cliente, e no caso de ser necessário, dependendo da quantidade de lógica de negócio que se pretenda colocar do lado do Vue, seria procurar uma framework de testes para Vue.

**Comment by ritosilva** [comment]
Tests for the services are implemented in spock.

So, far it is enough for what was needed, but may de interesting to explore in the future the feasibility and advantage of having tests for the UI implemented in Vue
